version: '3.3'

services:
  db:
    logging:
      driver: none
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    volumes:
      - /var/db:/data/db
      
  mq:
    logging:
      driver: none
    image: rabbitmq:3.9-management
    hostname: 'mq'
    expose:
      - "5672"
    ports:
      - "15672:15672"
    volumes:
      - "/var/mq:/var/lib/rabbitmq/mnesia"

  scheduler:
    build: 
      context: scheduler/
      dockerfile: Dockerfile
    image: scheduler
    depends_on:
      - db
      - mq
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_JOB_SCHEDULER_COLLECTION: ${MONGO_JOB_SCHEDULER_COLLECTION}
      MQ_BROKER_HOST: ${MQ_BROKER_HOST}
      MQ_BROKER_PORT: ${MQ_BROKER_PORT}
      MQ_QUEUE_NAME: ${MQ_QUEUE_NAME}
      MQ_EXCHANGE: ${MQ_EXCHANGE}

  api:
    build: 
      context: api/
      dockerfile: Dockerfile
    image: api
    ports:
      - "8000:8000"
    depends_on:
      - mq
      - db
      - scheduler
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_TIMER_STORAGE_COLLECTION: ${MONGO_TIMER_STORAGE_COLLECTION}
      MQ_BROKER_HOST: ${MQ_BROKER_HOST}
      MQ_BROKER_PORT: ${MQ_BROKER_PORT}
      MQ_QUEUE_NAME: ${MQ_QUEUE_NAME}